config/routes.rb
Rails.application.routes.draw do
  get 'payments/new'

  get 'payments/thanks'

 devise_for :users, controllers: {registrations: "registrations"}
  get 'home/index'

  resources :apuntes
  resources :leccions
  resources :plantillas
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :cursos
  resources :charges

  root 'home#index'


  resources :payments, only: [:new, :create]
  get 'payment-thanks', to: 'payments#thanks', as: 'payment_thanks'

 

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/plantilla.rb
class Plantilla < ApplicationRecord
	belongs_to :curso
end

app/controllers/plantillas_controller.rb
class PlantillasController < ApplicationController
  before_action :set_plantilla, only: [:show, :edit, :update, :destroy]

  # GET /plantillas
  # GET /plantillas.json
  def index
    @plantillas = Plantilla.all
  end

  # GET /plantillas/1
  # GET /plantillas/1.json
  def show
  end

  # GET /plantillas/new
  def new
    @plantilla = Plantilla.new
  end

  # GET /plantillas/1/edit
  def edit
  end

  # POST /plantillas
  # POST /plantillas.json
  def create
    @plantilla = Plantilla.new(plantilla_params)

    respond_to do |format|
      if @plantilla.save
        format.html { redirect_to @plantilla, notice: 'Plantilla was successfully created.' }
        format.json { render :show, status: :created, location: @plantilla }
      else
        format.html { render :new }
        format.json { render json: @plantilla.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /plantillas/1
  # PATCH/PUT /plantillas/1.json
  def update
    respond_to do |format|
      if @plantilla.update(plantilla_params)
        format.html { redirect_to @plantilla, notice: 'Plantilla was successfully updated.' }
        format.json { render :show, status: :ok, location: @plantilla }
      else
        format.html { render :edit }
        format.json { render json: @plantilla.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /plantillas/1
  # DELETE /plantillas/1.json
  def destroy
    @plantilla.destroy
    respond_to do |format|
      format.html { redirect_to plantillas_url, notice: 'Plantilla was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_plantilla
      @plantilla = Plantilla.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def plantilla_params
      params.require(:plantilla).permit(:title, :summary, :curso_id)
    end
end

app/helpers/plantillas_helper.rb
module PlantillasHelper
end

app/views/plantillas/_form.html.erb
<%= form_with(model: plantilla, local: true) do |form| %>
  <% if plantilla.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(plantilla.errors.count, "error") %> prohibited this plantilla from being saved:</h2>

      <ul>
      <% plantilla.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, id: :plantilla_title %>
  </div>

  <div class="field">
    <%= form.label :summary %>
    <%= form.text_area :summary, id: :plantilla_summary %>
  </div>

  <div class="field">
    <%= form.label :curso_id %>
    <%= form.number_field :curso_id, id: :plantilla_curso_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/plantillas/edit.html.erb
<h1>Editing Plantilla</h1>

<%= render 'form', plantilla: @plantilla %>

<%= link_to 'Show', @plantilla %> |
<%= link_to 'Back', plantillas_path %>

app/views/plantillas/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Plantillas</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Summary</th>
      <th>Curso</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @plantillas.each do |plantilla| %>
      <tr>
        <td><%= plantilla.title %></td>
        <td><%= plantilla.summary %></td>
        <td><%= plantilla.curso_id %></td>
        <td><%= link_to 'Show', plantilla %></td>
        <td><%= link_to 'Edit', edit_plantilla_path(plantilla) %></td>
        <td><%= link_to 'Destroy', plantilla, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Plantilla', new_plantilla_path %>

app/views/plantillas/new.html.erb
<h1>New Plantilla</h1>

<%= render 'form', plantilla: @plantilla %>

<%= link_to 'Back', plantillas_path %>

app/views/plantillas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @plantilla.title %>
</p>

<p>
  <strong>Summary:</strong>
  <%= @plantilla.summary %>
</p>

<p>
  <strong>Curso:</strong>
  <%= @plantilla.curso_id %>
</p>

<%= link_to 'Edit', edit_plantilla_path(@plantilla) %> |
<%= link_to 'Back', plantillas_path %>