config/routes.rb
Rails.application.routes.draw do
  get 'payments/new'

  get 'payments/thanks'

 devise_for :users, controllers: {registrations: "registrations"}
  get 'home/index'

  resources :apuntes
  resources :leccions
  resources :plantillas
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :cursos
  resources :charges

  root 'home#index'


  resources :payments, only: [:new, :create]
  get 'payment-thanks', to: 'payments#thanks', as: 'payment_thanks'

 

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/curso.rb
class Curso < ActiveRecord::Base
	has_many :plantillas
	has_many :leccions
  has_attached_file :icon, styles: {
    medium: '300x300>',
    thumb: '96x96!'
  }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :icon, content_type: /\Aimage\/.*\z/
end

app/controllers/cursos_controller.rb
class CursosController < ApplicationController
  before_action :set_curso, only: [:show, :edit, :update, :destroy]

  # GET /cursos
  # GET /cursos.json
  def index
    @cursos = Curso.all
  end

  # GET /cursos/1
  # GET /cursos/1.json
  def show
  end

  # GET /cursos/new
  #def new
  #  @curso = Curso.new
  #end

  # GET /cursos/1/edit
  #def edit
  #end

  # POST /cursos
  # POST /cursos.json
  def create
    @curso = Curso.new(curso_params)

    respond_to do |format|
      if @curso.save
        format.html { redirect_to @curso, notice: 'Curso was successfully created.' }
        format.json { render :show, status: :created, location: @curso }
      else
        format.html { render :new }
        format.json { render json: @curso.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cursos/1
  # PATCH/PUT /cursos/1.json
  def update
    respond_to do |format|
      if @curso.update(curso_params)
        format.html { redirect_to @curso, notice: 'Curso was successfully updated.' }
        format.json { render :show, status: :ok, location: @curso }
      else
        format.html { render :edit }
        format.json { render json: @curso.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cursos/1
  # DELETE /cursos/1.json
  def destroy
    @curso.destroy
    respond_to do |format|
      format.html { redirect_to cursos_url, notice: 'Curso was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_curso
      @curso = Curso.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def curso_params
      params.require(:curso).permit(:title, :summary, :content, :icon)
    end
end

app/helpers/cursos_helper.rb
module CursosHelper
end

app/views/cursos/_form.html.erb
<%= form_for @curso, url: cursos_path, html: { multipart: true } do |form| %>
  <% if curso.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(curso.errors.count, "error") %> prohibited this curso from being saved:</h2>

      <ul>
      <% curso.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, id: :curso_title %>
  </div>

  <div class="field">
    <%= form.label :summary %>
    <%= form.text_area :summary, id: :curso_summary %>
  </div>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_area :content, id: :curso_content %>
  </div>

  <div class="field">
    <%= form.label :icon %>
    <%= form.file_field :icon %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/cursos/edit.html.erb
<h1>Editing Curso</h1>

<%= render 'form', curso: @curso %>

<%= link_to 'Show', @curso %> |
<%= link_to 'Back', cursos_path %>

app/views/cursos/index.html.erb
<p id="notice"><%= notice %></p>

<nav class="navbar navbar-default" >
      <div class="container" id="navbar2">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar" id="tog">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="/"><img src="/assets/logo.fw.png" class="logo" alt="logo"></a>
        </div>

        <div  class="navbar-collapse collapse" id="navbar">
          <ul class="nav navbar-nav navbar-right" >
            <li><a href="/">Inicio</a></li>
            <li><a href="/">Cursos</a></li>
            <li><a href="/como-trabajamos">Apuntes</a></li>
            <li><a href="/trabajos">Plantillas</a></li>
          </ul>
        </div><!--/.nav-collapse -->
    </div>
  </nav>

  <div id="main2">
    <div class="container" >
      <h1 id="h1curso">Nuestros Cursos</h1>
      <img src="/assets/separator.fw.png" id="separator">
    </div>
  </div>

  <div id="main3">
    <div class="container" >
      <div class="row" >

        <% @cursos.each do |curso| %>
        <div class="col-md-6">
          <div id="white" class="shadow99">
            <%= image_tag curso.icon.url(:thumb), :id => "cursoimg" %>
            <div id="cursodiv">
              <h2 id="cursodivh2"><%= curso.title %></h2>
              <p id="cursodivp"><%= curso.summary %></p>
            </div>
            <div id="line"></div>
            <h2 id="cursodivh2">Lecciones</h2>
            <% curso.leccions.each do |leccion| %>
            <div class="block">
              <a id="cursoa" class="collapsed" role="button" data-toggle="collapse" data-parent="#accordion" href="#curso<%= leccion.id %>" aria-expanded="false" aria-controls="curso<%= leccion.id %>"><p id="cursodivp2"><%= leccion.title %></p><img src="/assets/arrow.fw.png" id="arrow2"></a>
              <div id="curso<%= leccion.id %>" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingTwo" >
                <div id="divp3"><p id="cursodivp3"><%= leccion.summary %></p></div>
              </div>
            </div>
            <% end %>
            
            <%= link_to 'Ir al curso', curso, :id => "boton" %>
          </div>
        </div>
        <% end %>
        
      </div>
    </div>
  </div>
        
  <footer>
  </footer>

app/views/cursos/new.html.erb
<h1>New Curso</h1>

<%= render 'form', curso: @curso %>

<%= link_to 'Back', cursos_path %>

app/views/cursos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @curso.title %>
</p>

<p>
  <strong>Summary:</strong>
  <%= @curso.summary %>
</p>

<p>
  <strong>Content:</strong>
  <%= @curso.content %>
</p>

<p>
  <strong>Icon:</strong>
  <%= image_tag @curso.icon.url(:thumb) %>
</p>

<%= link_to 'Edit', edit_curso_path(@curso) %> |
<%= link_to 'Back', cursos_path %>