config/routes.rb
Rails.application.routes.draw do
  get 'payments/new'

  get 'payments/thanks'

 devise_for :users, controllers: {registrations: "registrations"}
  get 'home/index'

  resources :apuntes
  resources :leccions
  resources :plantillas
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :cursos
  resources :charges

  root 'home#index'


  resources :payments, only: [:new, :create]
  get 'payment-thanks', to: 'payments#thanks', as: 'payment_thanks'

 

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/leccion.rb
class Leccion < ApplicationRecord
	belongs_to :curso
	has_many :apuntes
  has_attached_file :icon, styles: {
    medium: '300x300>',
    thumb: '96x96!'
  }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :icon, content_type: /\Aimage\/.*\z/
  has_attached_file :image, styles: {
    medium: '900x300>',
    thumb: '120x40!'
  }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
end

app/controllers/leccions_controller.rb
class LeccionsController < ApplicationController
  before_action :set_leccion, only: [:show, :edit, :update, :destroy]

  # GET /leccions
  # GET /leccions.json
  def index
    @leccions = Leccion.all
  end

  # GET /leccions/1
  # GET /leccions/1.json
  def show
  end

  # GET /leccions/new
  def new
    @leccion = Leccion.new
  end

  # GET /leccions/1/edit
  def edit
  end

  # POST /leccions
  # POST /leccions.json
  def create
    @leccion = Leccion.new(leccion_params)

    respond_to do |format|
      if @leccion.save
        format.html { redirect_to @leccion, notice: 'Leccion was successfully created.' }
        format.json { render :show, status: :created, location: @leccion }
      else
        format.html { render :new }
        format.json { render json: @leccion.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /leccions/1
  # PATCH/PUT /leccions/1.json
  def update
    respond_to do |format|
      if @leccion.update(leccion_params)
        format.html { redirect_to @leccion, notice: 'Leccion was successfully updated.' }
        format.json { render :show, status: :ok, location: @leccion }
      else
        format.html { render :edit }
        format.json { render json: @leccion.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /leccions/1
  # DELETE /leccions/1.json
  def destroy
    @leccion.destroy
    respond_to do |format|
      format.html { redirect_to leccions_url, notice: 'Leccion was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_leccion
      @leccion = Leccion.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def leccion_params
      params.require(:leccion).permit(:number, :title, :summary, :content, :video, :curso_id)
    end
end

app/helpers/leccions_helper.rb
module LeccionsHelper
end

app/views/leccions/_form.html.erb
<%= form_with(model: leccion, local: true) do |form| %>
  <% if leccion.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(leccion.errors.count, "error") %> prohibited this leccion from being saved:</h2>

      <ul>
      <% leccion.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :number %>
    <%= form.text_field :number, id: :leccion_number %>
  </div>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, id: :leccion_title %>
  </div>

  <div class="field">
    <%= form.label :summary %>
    <%= form.text_area :summary, id: :leccion_summary %>
  </div>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_area :content, id: :leccion_content %>
  </div>

  <div class="field">
    <%= form.label :video %>
    <%= form.text_field :video, id: :leccion_video %>
  </div>

  <div class="field">
    <%= form.label :curso_id %>
    <%= form.number_field :curso_id, id: :leccion_curso_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/leccions/edit.html.erb
<h1>Editing Leccion</h1>

<%= render 'form', leccion: @leccion %>

<%= link_to 'Show', @leccion %> |
<%= link_to 'Back', leccions_path %>

app/views/leccions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Leccions</h1>

<table>
  <thead>
    <tr>
      <th>Number</th>
      <th>Title</th>
      <th>Summary</th>
      <th>Content</th>
      <th>Video</th>
      <th>Curso</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @leccions.each do |leccion| %>
      <tr>
        <td><%= leccion.number %></td>
        <td><%= leccion.title %></td>
        <td><%= leccion.summary %></td>
        <td><%= leccion.content %></td>
        <td><%= leccion.video %></td>
        <td><%= leccion.curso_id %></td>
        <td><%= link_to 'Show', leccion %></td>
        <td><%= link_to 'Edit', edit_leccion_path(leccion) %></td>
        <td><%= link_to 'Destroy', leccion, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Leccion', new_leccion_path %>

app/views/leccions/new.html.erb
<h1>New Leccion</h1>

<%= render 'form', leccion: @leccion %>

<%= link_to 'Back', leccions_path %>

app/views/leccions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Number:</strong>
  <%= @leccion.number %>
</p>

<p>
  <strong>Title:</strong>
  <%= @leccion.title %>
</p>

<p>
  <strong>Summary:</strong>
  <%= @leccion.summary %>
</p>

<p>
  <strong>Content:</strong>
  <%= @leccion.content %>
</p>

<p>
  <strong>Video:</strong>
  <%= @leccion.video %>
</p>

<p>
  <strong>Curso:</strong>
  <%= @leccion.curso_id %>
</p>

<%= link_to 'Edit', edit_leccion_path(@leccion) %> |
<%= link_to 'Back', leccions_path %>