config/routes.rb
Rails.application.routes.draw do
  get 'payments/new'

  get 'payments/thanks'

 devise_for :users, controllers: {registrations: "registrations"}
  get 'home/index'

  resources :apuntes
  resources :leccions
  resources :plantillas
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :cursos
  resources :charges

  root 'home#index'


  resources :payments, only: [:new, :create]
  get 'payment-thanks', to: 'payments#thanks', as: 'payment_thanks'

 

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/apunte.rb
class Apunte < ApplicationRecord
	belongs_to :leccion
end

app/controllers/apuntes_controller.rb
class ApuntesController < ApplicationController
  before_action :set_apunte, only: [:show, :edit, :update, :destroy]

  # GET /apuntes
  # GET /apuntes.json
  def index
    @apuntes = Apunte.all
  end

  # GET /apuntes/1
  # GET /apuntes/1.json
  def show
  end

  # GET /apuntes/new
  def new
    @apunte = Apunte.new
  end

  # GET /apuntes/1/edit
  def edit
  end

  # POST /apuntes
  # POST /apuntes.json
  def create
    @apunte = Apunte.new(apunte_params)

    respond_to do |format|
      if @apunte.save
        format.html { redirect_to @apunte, notice: 'Apunte was successfully created.' }
        format.json { render :show, status: :created, location: @apunte }
      else
        format.html { render :new }
        format.json { render json: @apunte.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /apuntes/1
  # PATCH/PUT /apuntes/1.json
  def update
    respond_to do |format|
      if @apunte.update(apunte_params)
        format.html { redirect_to @apunte, notice: 'Apunte was successfully updated.' }
        format.json { render :show, status: :ok, location: @apunte }
      else
        format.html { render :edit }
        format.json { render json: @apunte.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /apuntes/1
  # DELETE /apuntes/1.json
  def destroy
    @apunte.destroy
    respond_to do |format|
      format.html { redirect_to apuntes_url, notice: 'Apunte was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_apunte
      @apunte = Apunte.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def apunte_params
      params.require(:apunte).permit(:content, :leccion_id)
    end
end

app/helpers/apuntes_helper.rb
module ApuntesHelper
end

app/views/apuntes/_form.html.erb
<%= form_with(model: apunte, local: true) do |form| %>
  <% if apunte.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(apunte.errors.count, "error") %> prohibited this apunte from being saved:</h2>

      <ul>
      <% apunte.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_area :content, id: :apunte_content %>
  </div>

  <div class="field">
    <%= form.label :leccion_id %>
    <%= form.number_field :leccion_id, id: :apunte_leccion_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/apuntes/edit.html.erb
<h1>Editing Apunte</h1>

<%= render 'form', apunte: @apunte %>

<%= link_to 'Show', @apunte %> |
<%= link_to 'Back', apuntes_path %>

app/views/apuntes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Apuntes</h1>

<table>
  <thead>
    <tr>
      <th>Content</th>
      <th>Leccion</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @apuntes.each do |apunte| %>
      <tr>
        <td><%= apunte.content %></td>
        <td><%= apunte.leccion_id %></td>
        <td><%= link_to 'Show', apunte %></td>
        <td><%= link_to 'Edit', edit_apunte_path(apunte) %></td>
        <td><%= link_to 'Destroy', apunte, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Apunte', new_apunte_path %>

app/views/apuntes/new.html.erb
<h1>New Apunte</h1>

<%= render 'form', apunte: @apunte %>

<%= link_to 'Back', apuntes_path %>

app/views/apuntes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Content:</strong>
  <%= @apunte.content %>
</p>

<p>
  <strong>Leccion:</strong>
  <%= @apunte.leccion_id %>
</p>

<%= link_to 'Edit', edit_apunte_path(@apunte) %> |
<%= link_to 'Back', apuntes_path %>